BX-Coding/patch-vm

- package.json
- src/linker/linker-constants.mjs
- src/linker/pyatch-linker.mjs
- src/virtual-machine.mjs
- src/worker/pyatch-worker.mjs
- src/worker/pyodide-web-worker.mjs
- test/integration/integration_motion.mjs
- test/linker/expected/multi-target-multithread-code-link-expected.py
- test/linker/expected/multiline-code-link-expected.py
- test/linker/expected/simple-code-link-expected.py
- test/linker/expected/single-target-multithread-code-link-expected.py
- test/linker/linker.mjs
- test/worker/python/single-target-changex.py
- test/worker/python/single-target-changey.py
- test/worker/python/single-target-glide.py
- test/worker/python/single-target-glideto.py
- test/worker/python/single-target-goto.py
- test/worker/python/single-target-gotoxy.py
- test/worker/python/single-target-ifonedgebounce.py
- test/worker/python/single-target-move.py
- test/worker/python/single-target-pointindirection.py
- test/worker/python/single-target-pointtowards.py
- test/worker/python/single-target-setrotationstyle.py
- test/worker/python/single-target-setx.py
- test/worker/python/single-target-sety.py
- test/worker/python/single-target-turnleft.py
- test/worker/python/single-target-turnright.py
- Large changes to linker made in order to integrate with VM
- VM motion integration suite was created and mostly passing
> Integration testing

- package.json
- src/engine/target.mjs
- src/serialization/sb3.mjs
- src/sprites/sprite.mjs
- src/worker/pyatch-worker.mjs
- src/worker/pyodide-web-worker.mjs
- test/worker/informal.mjs
- test/worker/worker.mjs
Previous changes were not regression tested. A lot of the changes broke the tests. Contains update to add sprite so it does not break everything :)
> Add Sprite Updated

- .eslintignore
- src/engine/block-utility.mjs
- src/engine/runtime.mjs
- src/io/clock.mjs
- src/io/keyboard.mjs
- src/io/mouse.mjs
- src/io/mouseWheel.mjs
- src/io/video.mjs
- src/virtual-machine.mjs
- test/scratch_vm/post_io.test.mjs
Add support for IO devices back to Patch VM. Added method vm.postData, blockUtil.ioQuery, back as well.
Needed for sensing and event implementation
test/scratch-vm/post_io.test.mjs
> feat: added support for runtime io devices

- .vscode/launch.json
- src/blocks/scratch3_looks.mjs
- test/primitives/blocks_looks.test.mjs
[BXC-114](https://linear.app/bxcoding/issue/BXC-114/changegraphiceffectby-color-bug)
> changeGraphicEffect Fix

- src/virtual-machine.mjs
Fixes `addCostume` in `VirtualMachine` class
> fix: virtual machine add costume

- src/virtual-machine.mjs
_What Github issue does this resolve (please include link)?_
_Describe what this Pull Request does_
_Explain why these changes should be made_
_Please show how you have added tests to cover your changes_
> feat: changes

- .vscode/launch.json
- package.json
- src/engine/thread.mjs
- src/worker/prim-proxy.js
- src/worker/pyatch-worker.mjs
- src/worker/pyodide-web.worker.mjs
- test/primitives/blocks_control.test.mjs
- test/primitives/blocks_events.test.mjs
- test/primitives/blocks_looks.test.mjs
- test/primitives/blocks_motion.test.mjs
- test/primitives/blocks_sensing.test.mjs
- test/primitives/blocks_sound.test.mjs
Extra headers no longer need to be set to enable stopping threads. SharedBufferArray no longer in use.
All tests passing
> feat: removed use of sharedbufferarray

- package.json
- src/engine/runtime.mjs
- src/engine/target.mjs
- src/virtual-machine.mjs
Quick additions to the vm api to support [BXC-145](https://linear.app/bxcoding/issue/BXC-145/save-all-green-flag)
> feat: added to vm api

- src/linker/pyatch-linker.mjs
- src/virtual-machine.mjs
- src/worker/prim-proxy.js
- src/worker/pyodide-web.worker.mjs
[BXC-149](https://linear.app/bxcoding/issue/BXC-149/refactor-autocomplete-feature)
Improves autocomplete
> Refactor Autocomplete

- package.json
- src/linker/pyatch-linker.mjs
- test/linker/expected/function-def-expected.py
- test/linker/input/function-def.py
- test/linker/linker.test.mjs
[BXC-152](https://linear.app/bxcoding/issue/BXC-152/add-async-tags-to-function-definitions)
Adds async keywords to function definitions on linking so that user-defined functions work as expected
Linker tests added
> feat: proper linking for definitions

- package.json
- src/blocks/scratch3_control.mjs
- src/worker/prim-proxy.js
- test/integration/integration_control.test.mjs
[BXC-148](https://linear.app/bxcoding/issue/BXC-148/implement-wait-block)
> feat: wait block implemented

- package.json
- src/worker/prim-proxy.js
[BXC-156](https://linear.app/bxcoding/issue/BXC-156/sound-blocks-not-making-sound)
> fix: correct playsound autofill

- src/virtual-machine.mjs
> feat: deleted uneeded backdrops functions

- src/engine/runtime.mjs
_What Github issue does this resolve (please include link)?_
_Describe what this Pull Request does_
_Explain why these changes should be made_
_Please show how you have added tests to cover your changes_
> fix: fix runtime's "stopThread" function

- .vscode/launch.json
- src/blocks/scratch3_control.mjs
- src/engine/block-utility.mjs
- src/engine/runtime.mjs
- src/engine/target.mjs
- src/engine/thread.mjs
- src/worker/pyatch-worker.mjs
- src/worker/pyodide-web.worker.mjs
- test/fixtures/reset-target.mjs
- test/integration/input/running-thread.py
- test/integration/input/shrinking-thread.py
- test/integration/integration_control.test.mjs
- test/integration/integration_hats.test.mjs
- test/integration/integration_thread.test.mjs
[BXC-161](https://linear.app/bxcoding/issue/BXC-161/zombie-while-loop-threads-bug)
Created a thread testing suite for thread functionality
> fix: thread restarts on flag clicked and load

- .vscode/launch.json
- src/engine/thread.mjs
- src/worker/pyatch-worker.mjs
- src/worker/pyodide-web.worker.mjs
- test/linker/expected/global-number-expected.py
- test/linker/expected/global-string-expected.py
- test/linker/linker.test.mjs
[BXC-172](https://linear.app/bxcoding/issue/BXC-172/global-variables-modification-bug)
Enabled global variable linker tests again
> feat: global variables available to all threads

- .vscode/launch.json
- src/blocks/scratch3_sensing.mjs
- test/integration/integration_sensing.test.mjs
[BXC-189](https://linear.app/bxcoding/issue/BXC-189/currently-asked-question-interrupt-bug)
Added a test to match the edge case
> fix: added and passed ask interrupt test

- src/blocks/scratch3_control.mjs
[BXC-191](https://linear.app/bxcoding/issue/BXC-191/stop-all-hangs-vm-execution)
Already covered
> fix: deleted the awaiting of stopall

- src/engine/runtime.mjs
- test/integration/integration_hats.test.mjs
[BXC-190](https://linear.app/bxcoding/issue/BXC-190/when-this-sprite-clicked-fires-all-listeners)
> fix: added this sprite clicked test case

- .vscode/launch.json
- src/virtual-machine.mjs
- src/worker/prim-proxy.js
- test/integration/autocomplete.test.mjs
Refactored all dynamic autocomplete functionality into the vm. Created some test cases for auto-complete as well.
[BXC-188](https://linear.app/bxcoding/issue/BXC-188/auto-complete-update)
> feat: dynamic autocomplete refactor

- .vscode/launch.json
- src/worker/prim-proxy.js
- test/integration/autocomplete.test.mjs
[BXC-188](https://linear.app/bxcoding/issue/BXC-188/auto-complete-update)
Bug discovered in recent PR. This has its fix.
Added two test cases for say autocompletion
> fix: created deep copy of api json

- src/blocks/scratch3_control.mjs
- src/sprites/rendered-target.mjs
- test/integration/integration_hats.test.mjs
[BXC-200](https://linear.app/bxcoding/issue/BXC-200/create-clone-bug)
> fix: when I start event

- src/worker/pyatch-worker.mjs
Removes arbitrary timeout of Pyodide load. Resolves #78
> Pyodide Load Timeout Fix

- package.json
- src/blocks/patch_core.mjs
- src/engine/runtime.mjs
- src/worker/prim-proxy.js
See [linear issue](https://linear.app/bxcoding/issue/PAT-250/patch-camp-features-hot-fix) for fixes
> feat: added fetch and lowered clone max

- package.json
- src/blocks/patch_core.mjs
fixed core_fetch header and body parameters. Now they just take json strings
> feat: fixed header and body methods
